alias bf="baw format"
alias cov="baw --test=cov --testconfig=+n=auto"
alias scov="cov --testconfig=+n=4"
alias scovlv="cov --testconfig=+n=4 --venv --test=long"
alias covv="baw --test=cov --venv --testconfig=+n=auto"
alias covl="baw --test=cov --test=long --testconfig=+n=auto"
alias covlv="baw --test=cov --test=long --venv --testconfig=+n=auto"
alias scovlv="covlv --testconfig=+n=4"
alias covn="baw --test=cov --test=nightly --testconfig=+n=auto"
alias covnv="baw --test=cov --test=nightly --venv --testconfig=+n=auto"
alias scovnv="covnv --testconfig=+n=4"

alias btg="baw test skip --generate"
alias btgv="baw --venv test skip --generate"
alias doc="baw doc"
alias drop="baw --drop"
alias format="baw format"
alias ide="baw --ide &"
alias gen="baw open generated"
alias open="explorer ."
alias patch="baw format && baw --testconfig=+n=auto release patch"
alias publish="baw publish"
alias release="baw --testconfig=+n=auto release "
alias srelease="baw --testconfig=+n=4 release "
alias upgrade="baw --upgrade --testconfig=+n=auto"
alias un="baw --notest upgrade "
alias uan="baw --notest upgrade all"
alias up="baw --notest --release=patch upgrade"
alias bi="baw --install"
alias bl="baw lint"
alias lf="baw --test --testconfig=\"+n=auto ++last+failed ++last+failed+no+failures none\""
alias bt="baw test"
alias btl="baw test long -n=6"
alias btn="baw test nightly -n=6"
alias btv="baw --venv test"
alias ff="baw --test --testconfig=\"+n=auto +x\" --venv"

alias btlv="baw --venv test long"
alias sbtlv="btlv --testconfig=+n=4"
alias ffbtlv="baw --test=long --testconfig=\"+n=auto +x\" --venv"
alias ffbt="baw  --test --testconfig=\"+n=auto +x\""
alias btnv="baw --test=nightly --testconfig=+n=auto --venv"
alias nightly="baw --venv test nightly -n=6"
alias snightly="nightly -n=4"
alias btt="baw test -n 1 -k "
alias bsd="baw sync dev"
alias bsm="baw sync all --minimal"
alias bsdv="baw sync dev --venv"
alias bsa="baw sync all && baw --venv sync all "
alias bttv="baw --venv test -k "
alias b="bttv"
alias bttl="baw test long -k "
alias bttlv="baw --venv test long -k "
alias bttn="baw test nightly -k "
alias bttnv="baw --venv test nightly -k "
alias bts="baw --test sync all"
alias btsv="baw --test --venv sync all"
alias bs="baw sync requirements"
alias bog="baw open generated"
alias bot="baw open tmp"
alias bc="baw clean"
alias bsv="baw --venv sync all"
alias setup="./setup.py install"

alias rt="baw clean resources"

alias pipi="baw install --remove --dev"
alias remove="pip uninstall --yes ."

alias tmp="baw open tmp"
alias venv="baw open venv"
alias blt="baw open lasttest"
