"""Base for generating project. Templates have to be here."""
from collections import namedtuple
from os.path import exists
from os.path import join

from baw import ROOT
from baw.utils import BAW_EXT
from baw.utils import file_read

FOLDERS = [
    BAW_EXT,
    'tests',
    'docs',
]

TEMPLATES = join(ROOT, 'templates')
assert exists(TEMPLATES), 'No template-dir %s' % TEMPLATES

WORKSPACE_TEMPLATE = join(TEMPLATES, '..code-workspace')
assert exists(WORKSPACE_TEMPLATE), 'No template %s' % WORKSPACE_TEMPLATE

GIT_IGNORE_TEMPLATE = join(TEMPLATES, '.gitignore')
assert exists(GIT_IGNORE_TEMPLATE), 'No gitignore %s' % GIT_IGNORE_TEMPLATE

README = """# $_SHORT_$ - $_NAME_$
"""

CHANGELOG = """# Changelog

Every noteable change is logged here.
"""

LICENCE = """# Licence
"""

TODO = """# TODO
"""

BUGS = """# BUGS
"""

REQUIREMENTS = ""

INIT = """from os.path import abspath
from os.path import dirname
from os.path import join

__version__ = '0.0.0'

THIS = dirname(__file__)
ROOT = abspath(join(THIS, '..'))
"""

CONF = """
# -*- coding: utf-8 -*-
#
# notes documentation build configuration file, created by
# sphinx-quickstart on Fri Nov 30 21:49:41 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
#import os
#from os.path import abspath, basename, dirname, join, exists
#import sys
#THIS = dirname(__file__)
#GENERATED = abspath(join(THIS, 'build'))  # object not found
#os.path.exists(GENERATED)
#sys.path.insert(0, join(THIS, '..'))

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.imgmath',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',
]

source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Notes'
copyright = '2018, Helmut Konrad Fahrendholz'
author = 'Helmut Konrad Fahrendholz'

# The short X.Y version.
version = '1812.1'
# The full version, including alpha/beta/rc tags.
release = '1812.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'default'

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'notesdoc'

# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/': None}

# Napoleon settings
napoleon_google_docstring = True
# napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
# napoleon_use_admonition_for_examples = True
# napoleon_use_admonition_for_notes = True
# napoleon_use_admonition_for_references = True
napoleon_use_ivar = True
# napoleon_use_param = True
napoleon_use_rtype = True
napoleon_use_keyword = True

"""

CODE_WORKSPACE = file_read(WORKSPACE_TEMPLATE)
GITIGNORE = file_read(join(TEMPLATES, '.gitignore'))
SETUP = file_read(join(TEMPLATES, 'setup.cfg'))

# None copies files
FILES = [
    ('.code-workspace', CODE_WORKSPACE),
    ('.gitignore', GITIGNORE),
    ('BUGS.md', BUGS),
    ('CHANGELOG.md', CHANGELOG),
    ('LICENCE.md', LICENCE),
    ('README.md', README),
    ('requirements.txt', REQUIREMENTS),
    ('TODO.md', TODO),
]
