#==============================================================================
# C O P Y R I G H T
#------------------------------------------------------------------------------
# Copyright (c) 2022-2023 by Helmut Konrad Schewe. All rights reserved.
# This file is property of Helmut Konrad Schewe. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
#==============================================================================

FROM {{baw_base}}

MAINTAINER HELMUT KONRAD FAHRENDHOLZ

ENV RUNJOB="exit 1"

ENTRYPOINT RUNJOB
