alias bf="baw format"
alias cov="baw test --cov -n=auto"
alias scov="cov -n=4"
alias covv="baw --venv test long"
alias covnv="baw --venv test nightly"

alias btg="baw test generate"
alias btgv="baw --venv test generate"
alias doc="baw doc"
alias drop="baw --drop"
alias format="baw format"
alias ide="baw ide &"
alias gen="baw open generated"
alias open="explorer ."
alias patch="baw format && baw --config=+n=auto release patch"
alias publish="baw publish"
alias release="baw --config=+n=auto release "
alias srelease="baw --config=+n=4 release "
alias upgrade="baw --upgrade --config=+n=auto"
alias un="baw upgrade "
alias uan="baw upgrade all"
alias up="baw --notest --release=patch upgrade"
alias bi="baw --install"
alias bl="baw lint"
alias lf="baw --test --config=\"+n=auto ++last+failed ++last+failed+no+failures none\""
alias bt="baw test"
alias btl="baw test long -n=6"
alias btn="baw test nightly -n=6"
alias btv="baw --venv test"
alias ff="baw --test --config=\"+n=auto +x\" --venv"

alias btlv="baw --venv test long"
alias sbtlv="btlv --config=+n=4"
alias ffbtlv="baw --test=long --config=\"+n=auto +x\" --venv"
alias ffbt="baw  --test --config=\"+n=auto +x\""
alias btnv="baw --test=nightly --config=+n=auto --venv"
alias nightly="baw --venv test nightly -n=6"
alias snightly="nightly -n=4"
alias btt="baw test -n 1 -k "
alias bsd="baw sync dev"
alias bsm="baw sync all --minimal"
alias bsdv="baw sync dev --venv"
alias bsa="baw sync all && baw --venv sync all "
alias bttv="baw --venv test -k "
alias b="bttv"
alias bttl="baw test long -k "
alias bttlv="baw --venv test long -k "
alias bttn="baw test nightly -k "
alias bttnv="baw --venv test nightly -k "
alias bts="baw --test sync all"
alias btsv="baw --test --venv sync all"
alias bs="baw sync requirements"
alias bog="baw open generated"
alias bot="baw open tmp"
alias bc="baw clean"
alias bsv="baw --venv sync all"
alias setup="pip install ."

alias rt="baw clean resources"

alias pipi="baw install --remove --dev"
alias remove="pip uninstall --yes ."

alias tmp="baw open tmp"
alias venv="baw open venv"
alias blt="baw open lasttest"
