#!/usr/bin/bash
# =============================================================================
# C O P Y R I G H T
# -----------------------------------------------------------------------------
# Copyright (c) 2023 by Helmut Konrad Schewe. All rights reserved.
# This file is property of Helmut Konrad Schewe. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
# =============================================================================

URL="${BASE}/${OWNER}/${REPO}.git"

: "${BRANCH}:=develop"
: "${WORKER}:=32"

echo "url:    ${URL}"
echo "branch: ${BRANCH}"
echo "worker: ${WORKER}"

echo "git clone ${URL} -b ${BRANCH} baseline && pushd baseline"
git clone ${URL} -b ${BRANCH} baseline && pushd baseline
if [ $? -ne 0 ]
then
    exit 1
fi

echo "baw --docken baseline test -n ${WORKER}"
baw --docken baseline test -n ${WORKER}
if [ $? -ne 0 ]
then
    exit 1
fi
