#!/usr/bin/bash
# =============================================================================
# C O P Y R I G H T
# -----------------------------------------------------------------------------
# Copyright (c) 2022-2023 by Helmut Konrad Schewe. All rights reserved.
# This file is property of Helmut Konrad Schewe. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
# =============================================================================

URL="${BASE}/${OWNER}/${REPO}.git"
echo $URL
echo $MAIN
git clone ${URL} -b ${MAIN} release && cd release
if [ $? -ne 0 ]
then
    exit 1
fi

echo 'baw sync'
baw sync all
if [ $? -ne 0 ]
then
    exit 1
fi

echo 'pip install...'
pip --verbose install .
if [ $? -ne 0 ]
then
    exit 1
fi

echo 'baw release...'
baw release --no_test --no_install --no_venv --no_linter --no_sync
if [ $? -ne 0 ]
then
    exit 1
fi

echo 'baw publish...'
baw publish
if [ $? -ne 0 ]
then
    exit 1
fi
