name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create release
        run: |
          make docker-release

      - name: Push commit and tag
        run: |
          git push origin main
          git push origin --tags
